print("This code is suposed to analize text ")
text = input("Input your text: ")
length = len(text)
numberofa = input("Input a letter that you want to count ")
first = input("Input an letter that you want to find first: ")
firstl = text.find(first)
last = input("Input an letter that you want to find last: ")
lasl = text.rfind(last)
upperver = text.upper()
lowerver = text.lower()
replacever = text.replace('a', '@')
print(f"The text length is {length}")
print(f"First chosen letter is {firstl} ")
print(f"Last chosen letter is {lasl} ")
print(f"{upperver}")
print(f"{lowerver}")
print(f"{replacever}")